{
 "title": "Topic Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Local publish rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Local publish throughput (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics - Producers - Subscriptions - Consumers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{topic=~\"$topic\"})",
     "legendFormat": "producers"
    },
    {
     "expr": "sum(pulsar_subscriptions_count{})",
     "legendFormat": "subscriptions"
    },
    { "expr": "sum(pulsar_consumers_count{})", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "Backlog Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_backlog_size{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "2nd Tier Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pulsar_storage_offloaded_size{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Storage entry size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(pulsar_entry_size_le_128{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 128 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_512{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 512 bytes"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_kb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 1 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_2_kb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 2 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_4_kb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 4 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_16_kb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 16 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_100_kb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 100 KB"
    },
    {
     "expr": "sum(pulsar_entry_size_le_1_mb{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "< 1 MB"
    },
    {
     "expr": "sum(pulsar_entry_size_overflow{topic=~\"$topic\"}) / 60.0",
     "legendFormat": "> 1 MB"
    }
   ]
  },
  {
   "title": "Storage Write Rate",
   "type": "timeseries",
   "description": "Rate of writes into storage (can be lower than publish rate, when batching is enabled)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_rate{topic=~\"$topic\"})",
     "legendFormat": "{{ topic }} "
    }
   ]
  },
  {
   "title": "Storage read entry rate",
   "type": "timeseries",
   "description": "Reads from bookies",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(pulsar_storage_read_rate{topic=~\"$topic\"})",
     "legendFormat": "{{ topic }} "
    }
   ]
  }
 ]
}