{
 "title": "Functions Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Received messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_function_received_total{name=~\"$function\"}[1m]))by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Successfully processed  messages",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_function_processed_successfully_total{name=~\"$function\" }[1m]))by (name)",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Average Processing latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_function_process_latency_ms_sum{name=~\"$function\"}[1m])) by (name)/sum(increase(pulsar_function_process_latency_ms_count{name=~\"$function\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "99pct Processing latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_function_process_latency_ms{quantile=\"0.99\", name=~\"$function\"}) by (name, instance_id)",
     "legendFormat": "{{ name }} - {{instance_id}}"
    }
   ]
  },
  {
   "title": "Number of instances",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(pulsar_function_system_exceptions_total{name=~\"$function\"})by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "User exceptions rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_function_user_exceptions_total{name=~\"$function\"}[1m]))by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "System exceptions rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_function_system_exceptions_total{name=~\"$function\"}[1m])) by (name)",
     "legendFormat": "{{ name }} "
    }
   ]
  },
  {
   "title": "User Exceptions",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "pulsar_function_user_exception{name=~\"$function\"}"
    }
   ]
  },
  {
   "title": "System Exceptions",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pulsar_function_system_exception{name=~\"$function\"}"
    }
   ]
  },
  {
   "title": "User Defined Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average User Defined Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pulsar_function_user_metric_sum{name=~\"$function\"}[1m])) by (metric, name)/sum(increase(pulsar_function_user_metric_count{name=~\"$function\"}[1m])) by (metric, name)",
     "legendFormat": "{{metric}}-{{name}}"
    }
   ]
  },
  {
   "title": "User Defined Metrics Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "metrics/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pulsar_function_user_metric_count{name=~\"$function\"}[1m])) by (metric, name)",
     "legendFormat": "{{metric}}-{{name}}"
    }
   ]
  }
 ]
}